server:
   servlet:
      context-path: /jpa-demo
spring:
   datasource:
      url: jdbc:postgresql://localhost:5432/demo
      username: postgres
      password: mstar123
      initialization-mode: never #always
      hikari:
         data-source-properties:
             useSSL: false
             createDatabaseIfNotExist: true
   jpa:
     database-platform: org.hibernate.dialect.PostgreSQLDialect
     show-sql: true
     open-in-view: false
     hibernate:
        ddl-auto: update
logging:
   level:
      com.spring.jpa: DEBUG
      org.hibernate: ERROR
      #Check Executed SQL Statements
      org.hibernate.sql: DEBUG 
      #Log Bind Parameter Values
      org.hibernate.type.descriptor.sql: TRACE
      org.springframework.web: ERROR      
management.endpoints.web.exposure.include: "*"
management.endpoints.web.exposure.exclude: "beans"
management.endpoint.health.show-details: always           